In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Created_dataset.csv')

In [3]:
df.head()

PID orignal Event1 Event2 Event3 Event4 Event5 Event6 Event7 Event8  \
0  1028890    2186   7087   4848   2214   7087   2214   2578   3074   7087   
1  1028890    7087   4848   2214   7087   2214   2578   3074   7087   2214   
2  1028890    4848   2214   7087   2214   2578   3074   7087   2214   2270   
3  1028890    2214   7087   2214   2578   3074   7087   2214   2270   1869   
4  1028890    7087   2214   2578   3074   7087   2214   2270   1869   2214   

  Event9 Event10  
0   2214    2270  
1   2270    1869  
2   1869    2214  
3   2214    7087  
4   7087    2186

In [4]:
train = df.iloc[:766776]

In [5]:
test = df[1:766777]

In [6]:
from sklearn.preprocessing import LabelEncoder
for c in train.columns:
    if train[c].dtype == 'object':
        lbl = LabelEncoder() 
        lbl.fit(list(train[c].values) + list(test[c].values)) 
        train[c] = lbl.transform(list(train[c].values))
        test[c] = lbl.transform(list(test[c].values))
print('Shape train: {}\nShape test: {}'.format(train.shape, test.shape))

/home/anirudh/anaconda/lib/python2.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
/home/anirudh/anaconda/lib/python2.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys


Shape train: (766776, 12)
Shape test: (766776, 12)


In [7]:
test.tail()

PID  orignal  Event1  Event2  Event3  Event4  Event5  Event6  \
766772  1022024     4483    4517    4244    2696    5221    4339    4337   
766773  1022024     4520    4251    2698    5229    4340    4341    4549   
766774  1022024     4254    2704    5233    4347    4342    4553    4550   
766775  1022024     2707    5240    4351    4349    4554    4554    4586   
766776  1022024     5243    4358    4353    4561    4555    4590    5060   

        Event7  Event8  Event9  Event10  
766772    4546    4543    4575     5047  
766773    4547    4579    5049     5016  
766774    4583    5053    5018     5036  
766775    5057    5022    5038     5053  
766776    5026    5042    5055     5030

In [8]:
from xgboost import XGBClassifier

/home/anirudh/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.neural_network import MLPClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.linear_model import LogisticRegression,PassiveAggressiveClassifier
from sklearn.tree import DecisionTreeClassifier

In [10]:
clf = OneVsRestClassifier(GaussianNB())

In [11]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 766776 entries, 0 to 766775
Data columns (total 12 columns):
PID        766776 non-null int64
orignal    766776 non-null int64
Event1     766776 non-null int64
Event2     766776 non-null int64
Event3     766776 non-null int64
Event4     766776 non-null int64
Event5     766776 non-null int64
Event6     766776 non-null int64
Event7     766776 non-null int64
Event8     766776 non-null int64
Event9     766776 non-null int64
Event10    766776 non-null int64
dtypes: int64(12)
memory usage: 70.2 MB


In [12]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 766776 entries, 1 to 766776
Data columns (total 12 columns):
PID        766776 non-null int64
orignal    766776 non-null int64
Event1     766776 non-null int64
Event2     766776 non-null int64
Event3     766776 non-null int64
Event4     766776 non-null int64
Event5     766776 non-null int64
Event6     766776 non-null int64
Event7     766776 non-null int64
Event8     766776 non-null int64
Event9     766776 non-null int64
Event10    766776 non-null int64
dtypes: int64(12)
memory usage: 70.2 MB


In [13]:
train_n=train.values

In [14]:
test_n=test.drop(['PID'],axis=1).values

In [15]:
train_n

array([[1028890,     657,    3760, ...,    3737,     669,     717],
       [1028890,    3763,    2668, ...,     669,     718,     420],
       [1028890,    2671,     677, ...,     718,     421,     668],
       ..., 
       [1022024,    4520,    4251, ...,    4579,    5049,    5016],
       [1022024,    4254,    2704, ...,    5053,    5018,    5036],
       [1022024,    2707,    5240, ...,    5022,    5038,    5053]])

In [16]:
test_n

array([[3763, 2668,  673, ...,  669,  718,  420],
       [2671,  677, 3754, ...,  718,  421,  668],
       [ 678, 3760,  673, ...,  421,  669, 3731],
       ..., 
       [4254, 2704, 5233, ..., 5053, 5018, 5036],
       [2707, 5240, 4351, ..., 5022, 5038, 5053],
       [5243, 4358, 4353, ..., 5042, 5055, 5030]])

In [17]:
from sklearn.model_selection import cross_val_predict,cross_val_score

In [18]:
#score_XG_L1 = cross_val_score(clf,train_n,test_n,cv=2,n_jobs=-1)
#print(score_XG_L1)

In [19]:
X = np.array([d[1:] for d in train_n])
Y = np.array([d[10] for d in test_n])

In [20]:
X

array([[ 657, 3760, 2662, ..., 3737,  669,  717],
       [3763, 2668,  673, ...,  669,  718,  420],
       [2671,  677, 3754, ...,  718,  421,  668],
       ..., 
       [4520, 4251, 2698, ..., 4579, 5049, 5016],
       [4254, 2704, 5233, ..., 5053, 5018, 5036],
       [2707, 5240, 4351, ..., 5022, 5038, 5053]])

In [21]:
X.shape

(766776, 11)

In [22]:
Y.shape

(766776,)

In [23]:
score_XG_L1 = cross_val_score(clf,X,Y,cv=2,n_jobs=-1)
print(score_XG_L1)

/home/anirudh/anaconda/lib/python2.7/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=2.
  % (min_groups, self.n_splits)), Warning)
Process PoolWorker-4:
Process PoolWorker-7:
Traceback (most recent call last):
  File "/home/anirudh/anaconda/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap


KeyboardInterrupt: 

In [24]:
y_pred = cross_val_predict(clf,X,Y,cv=7,n_jobs=-1)

/home/anirudh/anaconda/lib/python2.7/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=7.
  % (min_groups, self.n_splits)), Warning)


KeyboardInterrupt: 

In [25]:
from sklearn.metrics import mean_squared_error,r2_score

print(r2_score(Y,y_pred))
print(mean_squared_error(Y,y_pred))

NameError: name 'y_pred' is not defined

In [ ]:
from sklearn.metrics import classification_report
classification_report(Y,y_pred)

In [ ]:
y_pred_df = pd.DataFrame(data=y_pred)

In [ ]:
y_pred_df.head()

In [ ]:
y_pred

In [ ]:
list(y_pred)

In [ ]:
y_pred_t = lbl.inverse_transform(y_pred[0])

In [ ]:
y_pred[0]

In [ ]:
Y[0]

In [ ]:
y_pred_t[0]